[package]
name = "pokemon2rdf"
version = "0.2.0"
edition = "2021"

[dependencies]
chrono = "0.4"
indicatif = "0.18"
oxrdf = "0.3"
rustemon = { version = "4.3.0", default-features = false, features = ["serialize"] }
tokio = { version = "1.48", features = ["full"] }
