[package]
name = "pokemon2rdf"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.9"
oxrdf = "0.2.3"
rustemon = { version = "4.3.0", default-features = false, features = ["serialize"] }
serde_json = "1.0.122"
tempfile = "3.12.0"
tokio = { version = "1.39.2", features = ["full"] }
